In [1]:
import numpy as np # linear algebra
import pandas as pd
import pickle
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import MinMaxScaler

Heart= pd.read_csv('heart.csv')

In [4]:
from scipy.spatial.distance import cdist
#hacemos una copia del dataset original
data = Heart
#arreglo donde se guardaran los indices de los registros con valores atipicos
outliers = []
for j in range(len(data)):
    vecinos = 0
    # Obtener el registro actual del dataset
    registro_actual = data.iloc[j, :-1].values
    # Extraer las columnas del dataset
    dataset = data.iloc[:, :-1].values
    # Calcular las distancias entre el registro actual y los demÃ¡s registros del dataset
    distancias = cdist(registro_actual.reshape(1, -1), dataset)
    # Obtener las tres distancias mÃ¡s pequeÃ±as
    indices_mas_cercanos = np.argsort(distancias, axis=None)[:4]
    distancias_mas_cercanas = distancias[0, indices_mas_cercanos]
    l=0
    for l in range(3):
        aux = indices_mas_cercanos[l]
        if data['output'][j] != data['output'][aux]:
            vecinos += 1
        if vecinos >= 2:
            outliers.append(j)
print(outliers)
data=data.drop(outliers)
data

[5, 17, 25, 26, 27, 28, 31, 34, 36, 37, 39, 40, 43, 50, 52, 55, 63, 70, 79, 83, 84, 94, 95, 96, 101, 112, 120, 136, 137, 138, 139, 146, 151, 152, 155, 158, 172, 173, 182, 185, 188, 196, 199, 200, 205, 206, 212, 213, 219, 220, 229, 230, 236, 238, 241, 245, 247, 257, 258, 259, 264, 265, 267, 273, 275, 281, 283, 286, 287, 290, 292, 294, 302]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0

In [5]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
X = data.drop('output', axis=1)  # Seleccionar todas las columnas excepto la columna 'target'
y = data['output'] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=1)
nb_classifier = GaussianNB()
# Entrenar el clasificador en el conjunto de entrenamiento
nb_classifier.fit(X_train, y_train)
# Realizar predicciones en el conjunto de prueba
y_pred = nb_classifier.predict(X_test)
print(accuracy_score(y_pred,y_test))

0.8260869565217391

In [12]:
X

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3

In [20]:
pickle.dump(nb_classifier, open('model.pkl','wb'))
modelo = pickle.load(open('model.pkl','rb'))
print(modelo.predict([[57,0,0,120,354,0,1,163,1,0.6,2,0,2]]))
#print(accuracy_score(test1,y_test))

[1]

c:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(